import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "@/components/customNavbar/navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Estoria",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <header>
        <link rel="shortcut icon" href="../../../../../logo2.png" type="image/x-icon" />
      </header>
      <body className={`${inter.className} relative`}>
        <Providers>
          <NavBar/>
          {children}
          <Toaster/>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
