import NavBar from "../navbar"

export const metadata = {
  title: 'Estória | Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
